name: Generate JSDoc

on:
  push:
    branches:
      - dev/Jaques
      - final
      - master

jobs:
  generate-jsdoc:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3.5.2

      - name: Setup Node.js
        uses: actions/setup-node@v2.5.2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Generate JSDoc
        run: npx jsdoc -c jsdoc.config.json

      - name: Archive JSDoc as artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: jsdoc
          path: ./docs
